apiVersion: apps/v1
kind: Deployment
metadata:
  name: edureka-deployment
spec:
  selector:
    matchLabels:
      app: edureka-devops-project
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: edureka-devops-project
    spec:
      containers:
      - name: edureka-devops-project
        image: sersho1376/edu_devops:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

